---
title: "MIA EDA"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)

```

```{r}
mia <- read.csv("MIA Appeals and Grievances.csv")
```

```{r}
admin <- read.csv('Admin Complaints.csv')
```

```{r}
str(mia)
```

```{r}
names(mia) <- tolower(names(mia))
names(mia) <- gsub(' ',"_",names(mia))
names(mia) <- gsub("\\.", "_",names(mia))
```

```{r}
colnames(mia)
```

```{r}
colSums(is.na(mia))
```

```{r}
summary(mia)
```

```{r}
totals_only <- mia |>
  filter(company_name == "Total")
```

```{r}
str(admin)
```

```{r}
names(admin) <- tolower(names(admin))
names(admin) <- gsub(' ',"_",names(admin))
names(admin) <- gsub("\\.", "_",names(admin))
```

```{r}
admin_totals_only <- admin |>
  filter(type_of_procedure == "Total")
```

```{r}
colnames(admin)
```

```{r}
summary(admin)
```

# Adverse Decisions

```{r}
adp1 <- totals_only |>
  select(year,adverse_decisions_company_total)|>
  ggplot(aes(x = year, y = adverse_decisions_company_total)) +
  geom_line(color = "blue") +
  geom_point() +
  labs(
    title = "Total Amount of Adverse Decisions Over Time",
  caption = "Source: Maryland Insurance Administration")

adp1
```

```{r}
adverse_growth <- totals_only |>
  select(year,adverse_decisions_company_total) |>
  arrange(year)|>
  mutate(
    pct_change = (adverse_decisions_company_total - lag(adverse_decisions_company_total)) / lag(adverse_decisions_company_total) * 100
  )

adverse_growth
```

```{r}
top_companies_ad <- mia |>
  filter(`company_name` != "Total") |>
  group_by(`company_name`) |>
  summarise(total = sum(`adverse_decisions_company_total`, na.rm = TRUE)) |>
  arrange(desc(total)) |>
  head(10) |>
  ggplot(aes(x = reorder(`company_name`, total), y = total)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(
    title = "Top 10 Companies with Adverse Decisions 2021-2024",
    caption = 'Source: Maryland Insurance Administration',
    x = 'Company Name',
    y = 'Total'
  ) +
  theme(plot.title = element_text(size = 10, face = "bold"))

top_companies_ad
```

```{r}
totals_adverse_services <- totals_only |>
  select(
    year,
    adverse_decisions_inpatient_hospital_services_number,
    adverse_decisions_emergency_room_services_number,
    adverse_decisions_mental_health_services_number,
   adverse_decisions_physician_services_number,
  adverse_decisions_laboratory__radiology_services_number,
    adverse_decisions_pharmacy_services_number,
    adverse_decisions_pt__ot__st_services__incl_inpat_rehab__number_,
    adverse_decisions_skilled_nurse_faculty_sub_acute_nursing_home_number,
   adverse_decisions_durable_medical_equipment_services_number,
    adverse_decisions_dental_number,
    adverse_decisions_home_health_services_number,
    adverse_decisions_obesity__ivf__podiatry__hearing_and_vision_number_
  )
```

```{r}
totals_adverse_services_long <- totals_adverse_services |>
  pivot_longer(
    cols = -year,
    names_to = "service",
    values_to = "count"
  )
```

```{r}
adverse_service_growth <- totals_adverse_services_long |>
  arrange(service, year) |>
  group_by(service) |>
  mutate(
    pct_change = (count - lag(count)) / lag(count) * 100
  ) |>
  ungroup() 


adverse_service_growth
```

```{r}
ggplot(adverse_service_growth, aes(x = year, y = service, fill = pct_change)) +
  geom_tile(color = "white") +
  geom_text(aes(label = paste0(round(pct_change, 1), "%")), size = 3) +
  scale_fill_gradient2(
    name = "% Change"
  ) +
  labs(
    title = "Percent Change in Adverse Decisions by Service",
    caption = "Source: Maryland Insurance Administration"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8)
  )
```

```{r}
ggplot(totals_adverse_services_long, aes(x = year, y = count)) +
  geom_line( color = "darkgreen") +
  geom_point() +
  facet_wrap(~ service, scales = "free_y", ncol = 3) +
  labs(
    title = "Adverse Decisions by Service Over Time (2021-2024)",
    x = "Year",
    y = "Count",
    caption = "Source: Maryland Insurance Administration"
  ) +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 7, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 7)
  )
```

# Grievances

```{r}
grp1 <- totals_only |>
  select(year,grievances_filed_company_total)|>
  ggplot(aes(x = year, y = grievances_filed_company_total)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Total Amount of Grievances Over Time",
    caption = "Source: Maryland Insurance Administration"
  )
grp1
```

```{r}
grievance_growth <- totals_only |>
  select(year,grievances_filed_company_total) |>
  arrange(year) |>
  mutate(
    pct_change = (grievances_filed_company_total - lag(grievances_filed_company_total)) / lag(grievances_filed_company_total) * 100
  )

grievance_growth
```

```{r}
top_companies_gr <- mia |>
  filter(`company_name` != "Total") |>
  group_by(`company_name`) |>
  summarise(total = sum(`grievances_filed_company_total`, na.rm = TRUE)) |>
  arrange(desc(total)) |>
  head(10) |>
  ggplot(aes(x = reorder(`company_name`, total), y = total)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Top 10 Companies with Grievances 2021-2024",
       x = 'Company Name',
       y= 'Total',
       caption = "Source: Maryland Insurance Administration"
       ) 
top_companies_gr
  
```

```{r}
outcome <- mia |>
filter(`company_name` != "Total") |>
  summarise(
    upheld = sum(`grievances_upheld_number`, na.rm = TRUE),
    overturned = sum(`grievances_overturned_number`, na.rm = TRUE),
    modified = sum(`grievances_modified_number`, na.rm = TRUE)
  )|>
  pivot_longer(everything(), names_to = "outcome", values_to = "count") |>
  ggplot(aes(x = outcome, y = count, fill = outcome)) +
  geom_bar(stat = "identity") +
labs(
  title = "Grievances Outcome 202-2024",
  caption = "Source: Maryland Insurance Administration"
)
outcome
```

```{r}
totals_grievances_services <- totals_only |>
  select(
    year,
    grievance_inpatient_hospital_services_number,
    grievance_emergency_room_services_number,
    grievance_mental_health_services_number,
    grievance_physician_services_number,
    grievance_laboratory__radiology_services_number,
    grievance_pharmacy_services_number,
    grievance_pt__ot__st_services__incl_inpat_rehab__number_,
    grievance_skilled_nurse_faculty_sub_acute_nursing_home_number,
    grievance_durable_medical_equipment_services_number,
    grievance_dental_number,
    grievance_home_health_services_number,
    grievance_obesity__ivf__podiatry__hearing_and_vision_number_
  )
```

```{r}
totals_grievances_services_long <- totals_grievances_services |>
  pivot_longer(
    cols = -year,
    names_to = "service",
    values_to = "count"
  )
```

```{r}
grievance_service_growth <- totals_grievances_services_long |>
  arrange(service, year) |>
  group_by(service) |>
  mutate(
    pct_change = (count - lag(count)) / lag(count) * 100
  ) |>
  ungroup()

grievance_service_growth
```

```{r}
ggplot(grievance_service_growth, aes(x = year, y = service, fill = pct_change)) +
  geom_tile(color = "white") +
  geom_text(aes(label = paste0(round(pct_change, 1), "%")), size = 3) +
  scale_fill_gradient2(
    name = "% Change"
  ) +
  labs(
    title = "Percent Change in Grievances by Service",
    caption = "Source: Maryland Insurance Administration"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8)
  )
```

```{r}
ggplot(totals_grievances_services_long, aes(x = year, y = count)) +
  geom_line( color = "darkgreen") +
  geom_point() +
  facet_wrap(~ service, scales = "free_y", ncol = 3) +
  labs(
    title = "Grievances by Service Over Time (2021-2024)",
    x = "Year",
    y = "Count",
    caption = "Source: Maryland Insurance Administration"
  ) +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 7, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 7)
  )
```

```{r}
gr_outcome <- totals_only|>
select(year,grievances_overturned_number,grievances_upheld_number,grievances_modified_number)|>
   group_by(year) |>
  pivot_longer(-year, names_to = "outcome", values_to = "count") |>
  ggplot(aes(x = year, y = count, color = outcome)) +
  geom_line(size = 1) +
  geom_point()+
  labs(
    title = "Grievances Outcome"
  )
  gr_outcome

```

# Hospital Length Of Stay

```{r}
mia_los<- totals_only |>
select(year,grievances_upheld_number_for_hospital_los,grievances_overturned_number_for_hospital_los,grievances_modified_number_for_hospital_los)|>  group_by(year) |>
  pivot_longer(-year, names_to = "outcome", values_to = "count") |>
  ggplot(aes(x = year, y = count, color = outcome)) +
  geom_line(size = 1) +
  geom_point() +
  labs(
    title = "Grievances Outcome For Hospital Length of Stay",
    y = "Number of Cases",
    color = "Outcome",
    caption = "Source:Maryland Insurance Administration"
  )
mia_los
```

# Emergency Cases Resolution Hours

```{r}
emer_res <- totals_only|>
  select(year, emergency_cases___resolution_hours_1_st_quarter_,emergency_cases___resolution_hours_2nd_quarter_,emergency_cases___resolution_hours_3rd__quarter_,emergency_cases___resolution_hours_4th_quarter_) 
  
```

```{r}
emer_res_long <- emer_res |>
  pivot_longer(
    cols = -year,
    names_to = "Quarters",
    values_to = "Resolution_Hours"
  )
```

```{r}
eme_plot <- ggplot(emer_res_long, 
  aes(x = year, y = Resolution_Hours, fill = Quarters)) +
  geom_bar(stat = "identity", color = "black",
           position = position_dodge(width = 0.9)) +
  labs(
    title = "Quarterly Emergency Resolution Hours By Year",
    x = "Year",
    y = "Resolution Hours",
    fill = "Quarter",
    caption = "Source: Maryland Insurance Administration"
  ) +
  theme_minimal()

eme_plot
```

# Non-Emergency Cases Resolution Days

```{r}
non_emer_res <- totals_only|>
  select(year, non_emergency_cases___resolution_days_1st_quarter,non_emergency_cases___resolution_days_2nd_quarter,non_emergency_cases___resolution_days_3rd_quarter,non_emergency_cases___resolution_days_4th_quarter) 
```

```{r}
non_emer_res_long <- non_emer_res |>
  pivot_longer(
    cols = -year,
    names_to = "quarters",
    values_to = "resolution_Days"
  )
```

```{r}
non_eme_plot <- ggplot(non_emer_res_long, 
  aes(x = year, y = resolution_Days, fill = quarters)) +
  geom_bar(stat = "identity", color = "black",
           position = position_dodge(width = 0.9)) +
  labs(
    title = "Quarterly Emergency Resolution Days By Year",
    x = "Year",
    y = "Resolution Days",
    fill = "Quarter",
    caption = "Source: Maryland Insurance Administration"
  ) +
  theme_minimal()

non_eme_plot
```

# MIA Outcome

```{r}
mia_dec<- totals_only |>
  select(year,carrier_upheld_by_mia_number,carrier_modified_by_mia_number,carrier_reversed_by_mia_number)|>
  pivot_longer(-year, names_to = "outcome", values_to = "count") |>
  ggplot(aes(x = year, y = count, color = outcome)) +
  geom_line(size = 1) +
  geom_point() +
  labs(
    title = "MIA Decisions Over Time",
    y = "Number of Cases",
    color = "Outcome",
    caption = "Source: Maryland Insurance Administration"
  )
mia_dec

```

```{r}
admin |>
  filter(type_of_procedure != "TOTAL") |>
  pivot_longer(
    cols = c(carrier_upheld_by_mia_numner, 
             carrier_revesered_by_mia_number, 
             carrier_modifed_by_mia_numbner),
    names_to = "decision",
    values_to = "count"
  ) |>
  ggplot(aes(x = type_of_procedure, y = count, fill = decision)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  facet_wrap(~ year, ncol = 2) +
  labs(
    title = "MIA Appeal Decisions by Procedure Type (2021-2024)",
    x = "Type of Procedure",
    y = "Number of Decisions",
    fill = "Decision Type",
    caption = "Source: Maryland Insurance Administration"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 7))

```
